jobs:
  build:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./workflow/action

name: Ci

on:
  schedule:
    - cron: "0 */6 * * *"
